import { Query, QueryWithNames } from "@/types"

/*
 *==================================================
 * MARK:		   					     TYPES
 *==================================================
 */
/*
 *==================================================
 * MARK:						   COPY AND PASTE
 *==================================================

	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "",
		Container: "",
		Verified: false,
	},

 */

/*
 *==================================================
 * MARK:				🟪	🟧 	🟩  🩵  🟦     MAIN FILE
 *==================================================
 */

export const exampleQueries: (QueryWithNames | Query)[] = [
	// When Query sheet is "completed", remove Query from the type options above and change Verified to true, for Validated Verified and Required Alias.
	/*
	 *==================================================
	 * MARK:						         EXISTING
	 *==================================================
	 */
	{
		Marker: "name of this document",
		Text: "What is the name of this document?",
		Alias: "",
		Name: "docName",
		Container: "basic",
		Verified: true,
	},
	{
		Marker: "Service Comp Date",
		Text: "What is the Service Comp Date?",
		Alias: "dateOfHire",
		Name: "dateOfHire",
		Container: "basic",
		Verified: true,
	},
	{
		Marker: "Annual Salary",
		Text: "What is the Annual Salary?",
		Alias: "baseSalary",
		Name: "baseSalary",
		Container: "basic",
		Verified: true,
	},
	{
		Marker: "Net Pay x Current",
		Text: "What is the Current Net Pay?",
		Alias: "netTakeHome",
		Name: "netTakeHome",
		Container: "basic",
		Verified: true,
	},
	// {
	// 	Marker: "",
	// 	Text: "",
	// 	Alias: "fegliCoverage",
	// 	Name: "fegli.basic",
	// 	Container: "deduction",
	// 	Verified: false,
	// },
	// {
	// 	Marker: "",
	// 	Text: "",
	// 	Alias: "alotChecking",
	// 	Name: "alotChecking",
	// 	Container: "deduction",
	// 	Verified: false,
	// },
	// {
	// 	Marker: "",
	// 	Text: "",
	// 	Alias: "deductions.alotChecking",
	// 	Name: "alotChecking",
	// 	Container: "deduction",
	// 	Verified: false,
	// },
	// {
	// NO CURRENT EXAMPLE FOR THIS IN THE DOS FILE but plausible since the GSA file has it.
	// 	Marker: "DEDUCTIONS > Savings Allotments x Current",
	// 	Text: "What is the Current Savings Allotments?",
	// 	Alias: "deduction.alotSaving",
	// 	Name: "alotSaving",
	// 	Container: "deduction",
	// 	Verified: false,
	// },
	{
		Marker: "DEDUCTIONS > Vision x Current",
		Text: "In the DEDUCTIONS table what is the Current Vision?",
		Alias: "deduction.fdvv",
		Name: "fdvv",
		Container: "deduction",
		Verified: true,
	},
	{
		Marker: "DEDUCTIONS > Dental x Current",
		Text: "In the DEDUCTIONS table what is the Current Dental?",
		Alias: "deduction.fdvd",
		Name: "fdvd",
		Container: "deduction",
		Verified: true,
	},
	{
		Marker: "",
		Text: "",
		Alias: "tspContribution",
		Name: "tsp.contribution",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "healthInsurancePremium",
		Name: "healthInsurancePremium",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "currentLeaveBalance",
		Name: "currentAnnualLeaveBalance",
		Container: "leave",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "currentSickLeaveBalance",
		Name: "currentSickLeaveBalance",
		Container: "leave",
		Verified: false,
	},
	/*
	 *==================================================
	 * MARK:	             NOT ORIGINALLY INCLUDED
	 *==================================================
	 */
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "medicalBeforeTax",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "medicalEmployer",
		Container: "employer",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "dentalVision",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "dentalBeforeTax",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "dentalEmployer",
		Container: "employer",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "adsMgsSpa",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "coreLife",
		Container: "employer",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "lifeInsuranceTotal",
		Container: "benefit",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "suppLife",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "suppLifeEmployer",
		Container: "employer",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "_401k",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "_401k",
		Container: "employer",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "_401kAfterTax",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "suppLifeAfterTax",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.coverage",
		Container: "benefit",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.basic",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.basic",
		Container: "benefit",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.basic",
		Container: "employer",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.optionA",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.optionB",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.optionC",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "disability",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "federalCampaign",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "duesTVAEngineersAssoc",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "payPeriod",
		Container: "basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "payPeriodStart",
		Container: "basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "payPeriodEnd",
		Container: "basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "payPlanGradeStep",
		Container: "basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "payPlan",
		Container: "basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "payGrade",
		Container: "basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "payStep",
		Container: "basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "payPeriodHours",
		Container: "basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "oasdi",
		Container: "benefit",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "oasdi",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "retirement",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fsa",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "rate",
		Container: "basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fehb",
		Container: "benefit",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fedMedEE",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fedMedRR",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "withholding",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "withholdingFed",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "withholdingState",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.optional",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "tsp.basic",
		Container: "benefit",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "tsp.savings",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "tsp.loans",
		Container: "deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "tsp.matching",
		Container: "benefit",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fers",
		Container: "benefit",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "medicarePaidByGov",
		Container: "benefit",
		Verified: false,
	},
	/*
	 *==================================================
	 * MARK:						         CODES
	 *==================================================
	 */
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.bracketCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fehbCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fsaCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "annualLeaveCode",
		Container: "codes.basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "sickLeaveCode",
		Container: "codes.basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "otherLeaveCode",
		Container: "codes.basic",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "retirementCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "tsp.fersCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "oasdiCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.code",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "allotmentCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "fegli.optionalCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "tsp.loansCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "healthInsurancePremiumCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "medicareCode",
		Container: "codes.deduction",
		Verified: false,
	},
	{
		Marker: "",
		Text: "",
		Alias: "",
		Name: "organizationCode",
		Container: "codes.basic",
		Verified: false,
	},
]
